# Generated by Django 4.2.11 on 2024-05-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
